In [32]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import statsmodels.api as sm
from scipy import stats

# OLS on data generated through simulations for
        yi=b0+xb0i+ei
 where x in iidNr(u;suminf)and ei iid N(0, sig^2) for i= 1,.....n.        

In [33]:
sig = 0.5
nsim = 10
Tvec = [10,25,50,100,250]
nvec = [1,2,5]

holding_place_3b = np.zeros((nsim,len(Tvec),len(nvec)))
for ndx,n in enumerate(nvec):
    for tdx,T in enumerate(Tvec):
        for isim in range(nsim):
            sample =  np.random.permutation(2*T)
            train = sample[:int(T)]
            test = sample[int(T):]
            y = np.random.normal(0,sig,size=(2*T,1))
            x = np.random.normal(0,sig,size=(2*T,n))
            x = sm.add_constant(x)
            model = smf.OLS(y[train],x[train]).fit()
            mspe = ((y[test]-model.predict(x[test]))**2).mean()
            holding_place_3b[isim,tdx,ndx] = mspe
print(holding_place_3b.mean(0))

[[0.2495403  0.3883524  0.80189896]
 [0.2545234  0.27995906 0.3476975 ]
 [0.28331913 0.26308753 0.28265065]
 [0.2642353  0.25957548 0.25245774]
 [0.2502259  0.25867371 0.26598861]]


In [ ]:
# It can be seen that from the above results the mean square error reduces with increase 
# in number of variables

# OLS with 2,5 and 10 k-folds on DGP and different bias for eq.
                         yi=b0+xb0i+ei
     where x in iidNr(u;suminf)and ei iid N(0, sig^2) for i= 1,.....n.        

In [300]:
sig = 0.5
nsim = 10
Tvec = [10,25,50,100,250]
kvec = [2,5,10]
nvec = [1,2,5]
bvec = [-1,0,1]
holding_place_3b = np.zeros((nsim,len(Tvec),len(nvec),len(kvec)))
for bdx,c in enumerate(bvec):
    for kdx,k in enumerate(kvec):
        for ndx,n in enumerate(nvec):
            for tdx,T in enumerate(Tvec):
                for isim in range(nsim):
                    mspe = np.zeros(k)
                    for j in range(k):    
                            sample =  np.random.permutation(2*T)
                            train = sample[:int(T)]
                            test = sample[int(T):]
                            train_l = sample[:int((k-1-j)*T/k)]
                            train_u = sample[int((k-j)*T/k):]
                            train = np.concatenate((train_l,train_u),0)
                            test = sample[int((k-1-j)*T/k):int((k-j)*T/k)]
                            sample =  np.random.permutation(T)
                            train = sample[:int(T/2)]
                            test = sample[int(T/2):]
                            x = np.random.normal(0,sig,size=(T,n))
                            b = np.ones((n,1))*bvec[bdx]
                            tg= x.dot(b)
                            y = x.dot(b) + np.random.normal(0,sig,size=(T,1))
                            model = smf.OLS(y[train],x[train]).fit()
                            mspe [j] = ((y[test]-model.predict(x[test]))**2).mean()
                    holding_place_3b[isim,tdx,ndx,kdx]=mspe.mean()
    print("The values below are  mean and standarad deviation for B ",c)
    print(holding_place_3b.mean(0)[:,:,0])
    print(holding_place_3b.mean(0)[:,:,1])
    print(holding_place_3b.mean(0)[:,:,2])
    print()
    print()
    print(holding_place_3b.std(0)[:,:,0])
    print(holding_place_3b.std(0)[:,:,1])
    print(holding_place_3b.std(0)[:,:,2])

The values below are  mean and standarad deviation for B  -1
[[ 0.99445492  1.33034641 67.42429273]
 [ 0.67151403  1.26809374  2.34825254]
 [ 0.70911341  1.20416512  2.51350772]
 [ 0.73107905  1.2223815   2.60850233]
 [ 0.76712755  1.25899037  2.63581508]]
[[ 0.83841215  1.1851496  38.32357074]
 [ 0.69661308  1.19446991  2.9664375 ]
 [ 0.7611566   1.25710054  2.84793386]
 [ 0.72122912  1.21137184  2.67947973]
 [ 0.7467331   1.2618619   2.77193408]]
[[7.76848210e-01 1.11414370e+00 1.49357836e+03]
 [7.30030044e-01 1.16814176e+00 2.73661855e+00]
 [7.05418966e-01 1.18290842e+00 2.75446544e+00]
 [7.48327281e-01 1.21481811e+00 2.72014304e+00]
 [7.61503126e-01 1.21745826e+00 2.71794871e+00]]


[[4.56718065e-01 6.52828781e-01 1.87481211e+02]
 [1.64630468e-01 4.53129621e-01 3.57337365e-01]
 [1.23659922e-01 2.09321665e-01 3.43300755e-01]
 [1.09368674e-01 1.78202392e-01 3.72545516e-01]
 [4.22948249e-02 1.07380363e-01 2.41789906e-01]]
[[2.80128852e-01 3.63849008e-01 6.62182834e+01]
 [1.64516938e-0

In [ ]:
# It can be seen from the above simulation that with the increase in k folds the mean squared error 
# reduces